/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as nonPublicDashboardRouteRouteImport } from './routes/(non-public)/dashboard/route'
import { Route as nonPublicDashboardProjectIdRouteRouteImport } from './routes/(non-public)/dashboard/$projectId/route'
import { Route as nonPublicDashboardoverviewIndexRouteImport } from './routes/(non-public)/dashboard/(overview)/index'
import { Route as nonPublicDashboardProjectIdIndexRouteImport } from './routes/(non-public)/dashboard/$projectId/index'
import { Route as nonPublicDashboardProjectIdFeatureFeatureIdIndexRouteImport } from './routes/(non-public)/dashboard/$projectId/feature/$featureId/index'

const nonPublicRouteLazyRouteImport = createFileRoute('/(non-public)')()
const nonPublicSignUpIndexLazyRouteImport = createFileRoute(
  '/(non-public)/sign-up/',
)()
const nonPublicSignInIndexLazyRouteImport = createFileRoute(
  '/(non-public)/sign-in/',
)()
const nonPublicDashboardProjectsIndexLazyRouteImport = createFileRoute(
  '/(non-public)/dashboard/projects/',
)()
const nonPublicDashboardDocumentsIndexLazyRouteImport = createFileRoute(
  '/(non-public)/dashboard/documents/',
)()

const nonPublicRouteLazyRoute = nonPublicRouteLazyRouteImport
  .update({
    id: '/(non-public)',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(non-public)/route.lazy').then((d) => d.Route))
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const nonPublicDashboardRouteRoute = nonPublicDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => nonPublicRouteLazyRoute,
} as any)
const nonPublicSignUpIndexLazyRoute = nonPublicSignUpIndexLazyRouteImport
  .update({
    id: '/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => nonPublicRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(non-public)/sign-up/index.lazy').then((d) => d.Route),
  )
const nonPublicSignInIndexLazyRoute = nonPublicSignInIndexLazyRouteImport
  .update({
    id: '/sign-in/',
    path: '/sign-in/',
    getParentRoute: () => nonPublicRouteLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(non-public)/sign-in/index.lazy').then((d) => d.Route),
  )
const nonPublicDashboardProjectIdRouteRoute =
  nonPublicDashboardProjectIdRouteRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => nonPublicDashboardRouteRoute,
  } as any)
const nonPublicDashboardProjectsIndexLazyRoute =
  nonPublicDashboardProjectsIndexLazyRouteImport
    .update({
      id: '/projects/',
      path: '/projects/',
      getParentRoute: () => nonPublicDashboardRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(non-public)/dashboard/projects/index.lazy').then(
        (d) => d.Route,
      ),
    )
const nonPublicDashboardDocumentsIndexLazyRoute =
  nonPublicDashboardDocumentsIndexLazyRouteImport
    .update({
      id: '/documents/',
      path: '/documents/',
      getParentRoute: () => nonPublicDashboardRouteRoute,
    } as any)
    .lazy(() =>
      import('./routes/(non-public)/dashboard/documents/index.lazy').then(
        (d) => d.Route,
      ),
    )
const nonPublicDashboardoverviewIndexRoute =
  nonPublicDashboardoverviewIndexRouteImport.update({
    id: '/(overview)/',
    path: '/',
    getParentRoute: () => nonPublicDashboardRouteRoute,
  } as any)
const nonPublicDashboardProjectIdIndexRoute =
  nonPublicDashboardProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => nonPublicDashboardProjectIdRouteRoute,
  } as any)
const nonPublicDashboardProjectIdFeatureFeatureIdIndexRoute =
  nonPublicDashboardProjectIdFeatureFeatureIdIndexRouteImport.update({
    id: '/feature/$featureId/',
    path: '/feature/$featureId/',
    getParentRoute: () => nonPublicDashboardProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof nonPublicDashboardRouteRouteWithChildren
  '/': typeof publicIndexRoute
  '/dashboard/$projectId': typeof nonPublicDashboardProjectIdRouteRouteWithChildren
  '/sign-in/': typeof nonPublicSignInIndexLazyRoute
  '/sign-up/': typeof nonPublicSignUpIndexLazyRoute
  '/dashboard/$projectId/': typeof nonPublicDashboardProjectIdIndexRoute
  '/dashboard/': typeof nonPublicDashboardoverviewIndexRoute
  '/dashboard/documents/': typeof nonPublicDashboardDocumentsIndexLazyRoute
  '/dashboard/projects/': typeof nonPublicDashboardProjectsIndexLazyRoute
  '/dashboard/$projectId/feature/$featureId/': typeof nonPublicDashboardProjectIdFeatureFeatureIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/sign-in': typeof nonPublicSignInIndexLazyRoute
  '/sign-up': typeof nonPublicSignUpIndexLazyRoute
  '/dashboard/$projectId': typeof nonPublicDashboardProjectIdIndexRoute
  '/dashboard': typeof nonPublicDashboardoverviewIndexRoute
  '/dashboard/documents': typeof nonPublicDashboardDocumentsIndexLazyRoute
  '/dashboard/projects': typeof nonPublicDashboardProjectsIndexLazyRoute
  '/dashboard/$projectId/feature/$featureId': typeof nonPublicDashboardProjectIdFeatureFeatureIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(non-public)': typeof nonPublicRouteLazyRouteWithChildren
  '/(non-public)/dashboard': typeof nonPublicDashboardRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(non-public)/dashboard/$projectId': typeof nonPublicDashboardProjectIdRouteRouteWithChildren
  '/(non-public)/sign-in/': typeof nonPublicSignInIndexLazyRoute
  '/(non-public)/sign-up/': typeof nonPublicSignUpIndexLazyRoute
  '/(non-public)/dashboard/$projectId/': typeof nonPublicDashboardProjectIdIndexRoute
  '/(non-public)/dashboard/(overview)/': typeof nonPublicDashboardoverviewIndexRoute
  '/(non-public)/dashboard/documents/': typeof nonPublicDashboardDocumentsIndexLazyRoute
  '/(non-public)/dashboard/projects/': typeof nonPublicDashboardProjectsIndexLazyRoute
  '/(non-public)/dashboard/$projectId/feature/$featureId/': typeof nonPublicDashboardProjectIdFeatureFeatureIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/dashboard/$projectId'
    | '/sign-in/'
    | '/sign-up/'
    | '/dashboard/$projectId/'
    | '/dashboard/'
    | '/dashboard/documents/'
    | '/dashboard/projects/'
    | '/dashboard/$projectId/feature/$featureId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$projectId'
    | '/dashboard'
    | '/dashboard/documents'
    | '/dashboard/projects'
    | '/dashboard/$projectId/feature/$featureId'
  id:
    | '__root__'
    | '/(non-public)'
    | '/(non-public)/dashboard'
    | '/(public)/'
    | '/(non-public)/dashboard/$projectId'
    | '/(non-public)/sign-in/'
    | '/(non-public)/sign-up/'
    | '/(non-public)/dashboard/$projectId/'
    | '/(non-public)/dashboard/(overview)/'
    | '/(non-public)/dashboard/documents/'
    | '/(non-public)/dashboard/projects/'
    | '/(non-public)/dashboard/$projectId/feature/$featureId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  nonPublicRouteLazyRoute: typeof nonPublicRouteLazyRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(non-public)': {
      id: '/(non-public)'
      path: '/'
      fullPath: ''
      preLoaderRoute: typeof nonPublicRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(non-public)/dashboard': {
      id: '/(non-public)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof nonPublicDashboardRouteRouteImport
      parentRoute: typeof nonPublicRouteLazyRoute
    }
    '/(non-public)/sign-up/': {
      id: '/(non-public)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof nonPublicSignUpIndexLazyRouteImport
      parentRoute: typeof nonPublicRouteLazyRoute
    }
    '/(non-public)/sign-in/': {
      id: '/(non-public)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof nonPublicSignInIndexLazyRouteImport
      parentRoute: typeof nonPublicRouteLazyRoute
    }
    '/(non-public)/dashboard/$projectId': {
      id: '/(non-public)/dashboard/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/$projectId'
      preLoaderRoute: typeof nonPublicDashboardProjectIdRouteRouteImport
      parentRoute: typeof nonPublicDashboardRouteRoute
    }
    '/(non-public)/dashboard/projects/': {
      id: '/(non-public)/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof nonPublicDashboardProjectsIndexLazyRouteImport
      parentRoute: typeof nonPublicDashboardRouteRoute
    }
    '/(non-public)/dashboard/documents/': {
      id: '/(non-public)/dashboard/documents/'
      path: '/documents'
      fullPath: '/dashboard/documents/'
      preLoaderRoute: typeof nonPublicDashboardDocumentsIndexLazyRouteImport
      parentRoute: typeof nonPublicDashboardRouteRoute
    }
    '/(non-public)/dashboard/(overview)/': {
      id: '/(non-public)/dashboard/(overview)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof nonPublicDashboardoverviewIndexRouteImport
      parentRoute: typeof nonPublicDashboardRouteRoute
    }
    '/(non-public)/dashboard/$projectId/': {
      id: '/(non-public)/dashboard/$projectId/'
      path: '/'
      fullPath: '/dashboard/$projectId/'
      preLoaderRoute: typeof nonPublicDashboardProjectIdIndexRouteImport
      parentRoute: typeof nonPublicDashboardProjectIdRouteRoute
    }
    '/(non-public)/dashboard/$projectId/feature/$featureId/': {
      id: '/(non-public)/dashboard/$projectId/feature/$featureId/'
      path: '/feature/$featureId'
      fullPath: '/dashboard/$projectId/feature/$featureId/'
      preLoaderRoute: typeof nonPublicDashboardProjectIdFeatureFeatureIdIndexRouteImport
      parentRoute: typeof nonPublicDashboardProjectIdRouteRoute
    }
  }
}

interface nonPublicDashboardProjectIdRouteRouteChildren {
  nonPublicDashboardProjectIdIndexRoute: typeof nonPublicDashboardProjectIdIndexRoute
  nonPublicDashboardProjectIdFeatureFeatureIdIndexRoute: typeof nonPublicDashboardProjectIdFeatureFeatureIdIndexRoute
}

const nonPublicDashboardProjectIdRouteRouteChildren: nonPublicDashboardProjectIdRouteRouteChildren =
  {
    nonPublicDashboardProjectIdIndexRoute:
      nonPublicDashboardProjectIdIndexRoute,
    nonPublicDashboardProjectIdFeatureFeatureIdIndexRoute:
      nonPublicDashboardProjectIdFeatureFeatureIdIndexRoute,
  }

const nonPublicDashboardProjectIdRouteRouteWithChildren =
  nonPublicDashboardProjectIdRouteRoute._addFileChildren(
    nonPublicDashboardProjectIdRouteRouteChildren,
  )

interface nonPublicDashboardRouteRouteChildren {
  nonPublicDashboardProjectIdRouteRoute: typeof nonPublicDashboardProjectIdRouteRouteWithChildren
  nonPublicDashboardoverviewIndexRoute: typeof nonPublicDashboardoverviewIndexRoute
  nonPublicDashboardDocumentsIndexLazyRoute: typeof nonPublicDashboardDocumentsIndexLazyRoute
  nonPublicDashboardProjectsIndexLazyRoute: typeof nonPublicDashboardProjectsIndexLazyRoute
}

const nonPublicDashboardRouteRouteChildren: nonPublicDashboardRouteRouteChildren =
  {
    nonPublicDashboardProjectIdRouteRoute:
      nonPublicDashboardProjectIdRouteRouteWithChildren,
    nonPublicDashboardoverviewIndexRoute: nonPublicDashboardoverviewIndexRoute,
    nonPublicDashboardDocumentsIndexLazyRoute:
      nonPublicDashboardDocumentsIndexLazyRoute,
    nonPublicDashboardProjectsIndexLazyRoute:
      nonPublicDashboardProjectsIndexLazyRoute,
  }

const nonPublicDashboardRouteRouteWithChildren =
  nonPublicDashboardRouteRoute._addFileChildren(
    nonPublicDashboardRouteRouteChildren,
  )

interface nonPublicRouteLazyRouteChildren {
  nonPublicDashboardRouteRoute: typeof nonPublicDashboardRouteRouteWithChildren
  nonPublicSignInIndexLazyRoute: typeof nonPublicSignInIndexLazyRoute
  nonPublicSignUpIndexLazyRoute: typeof nonPublicSignUpIndexLazyRoute
}

const nonPublicRouteLazyRouteChildren: nonPublicRouteLazyRouteChildren = {
  nonPublicDashboardRouteRoute: nonPublicDashboardRouteRouteWithChildren,
  nonPublicSignInIndexLazyRoute: nonPublicSignInIndexLazyRoute,
  nonPublicSignUpIndexLazyRoute: nonPublicSignUpIndexLazyRoute,
}

const nonPublicRouteLazyRouteWithChildren =
  nonPublicRouteLazyRoute._addFileChildren(nonPublicRouteLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  nonPublicRouteLazyRoute: nonPublicRouteLazyRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
